[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
    REACT_APP_URL = "https://flowhome-server.herokuapp.com/api"
[context.branch-deploy.environment]
    REACT_APP_URL = "https://flowhome-server.herokuapp.com/api"
[context.deploy-preview.environment]
    REACT_APP_URL = "https://flowhome-server.herokuapp.com/api"